version: 1
scan:
  issues: true

allowed-users:
  - matteogabriele
  - graphieros
  - huang-julien

honeypot: true
auto-close: true
messages:
  automation: |-
    Your account has been detected as possibly automated, and this PR has been automatically closed.

    This is an automation-free zone — no droids allowed.

    ![](https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNGhoOHVidmo4cmxlNmp6enY3Y2NkZWduNHZzYXM1bmpxbTFtOWhheSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xT9DPr4VjeCgeiLoMo/giphy.gif)
