import type { GitHubCommit } from "./types";

const AI_COMMIT_PATTERNS: RegExp[] = [
	/co-authored-by:.*<[^>]*@anthropic\.com>/i,
	/co-authored-by:.*<[^>]*copilot@github\.com>/i,
	/co-authored-by:.*<[^>]*\+copilot@users\.noreply\.github\.com>/i,
	/co-authored-by:\s*github copilot\b/i,
	/co-authored-by:.*<[^>]*@cursor\.com>/i,
	/co-authored-by:.*devin-ai-integration/i,
	/co-authored-by:\s*devin ai\b/i,
	/co-authored-by:.*<[^>]*@openai\.com>/i,
	/co-authored-by:\s*openai[- ]codex\b/i,
	/co-authored-by:\s*aider\s*[(<]/i,
	/co-authored-by:.*openhands-agent/i,
	/co-authored-by:.*<[^>]*@sourcegraph\.com>/i,
	/generated with \[?claude code/i,
	/🤖 generated with/i,
	/generated by cursor/i,
];

export function hasAICommitMetadata(
	message: string | undefined | null,
): boolean {
	if (!message) return false;
	return AI_COMMIT_PATTERNS.some((re) => re.test(message));
}

export type CommitMetadataStats = {
	totalCommits: number;
	aiCommits: number;
	ratio: number;
};

export function analyzeCommitMetadata(
	commits: GitHubCommit[],
): CommitMetadataStats {
	const seen = new Set<string>();
	let totalCommits = 0;
	let aiCommits = 0;

	for (const commit of commits) {
		if (commit.sha) {
			if (seen.has(commit.sha)) continue;
			seen.add(commit.sha);
		}
		totalCommits++;
		if (hasAICommitMetadata(commit.message)) {
			aiCommits++;
		}
	}

	const ratio = totalCommits > 0 ? aiCommits / totalCommits : 0;

	return {
		totalCommits,
		aiCommits,
		ratio,
	};
}
